name: Deploy Infrastructure and Run Security Audit

on:
  push:
    branches: [ "main" ]

jobs:
  # Job 1: Runs Terraform code inside this repository
  deploy_infrastructure:
    runs-on: ubuntu-latest
    outputs:
      target_ip: ${{ steps.extract_ip.outputs.target_ip }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Terraform Init & Apply
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Extract Target IP Output
        id: extract_ip
        run: echo "target_ip=$(terraform output -raw instance_public_ip)" >> $GITHUB_OUTPUT

  # Job 2: Reaches out to the CENTRAL REPO to run Nmap & OpenVAS scans
  trigger_security_scan:
    needs: deploy_infrastructure
    uses: TholiweKhoza/central-security-repo/.github/workflows/gcp-security-scan.yml@main
    with:
      target_ip: ${{ needs.deploy_infrastructure.outputs.target_ip }}
      report_bucket: ${{ needs.deploy_infrastructure.outputs.scan_bucket }}
    secrets: inherit 